version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: videome-mongodb-dev
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
    networks:
      - videome-network-dev

  # Backend service for development (with hot reload)
  server:
    image: node:18-alpine
    container_name: videome-server-dev
    working_dir: /app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USER:-root}:${MONGO_PASSWORD:-password}@mongodb:27017/videome?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-thisisasecretkey}
      - JWT_EXPIRE=${JWT_EXPIRE:-30d}
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    networks:
      - videome-network-dev
    command: sh -c "npm install && npm run dev"

  # Frontend service for development (with hot reload)
  client:
    image: node:18-alpine
    container_name: videome-client-dev
    working_dir: /app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    depends_on:
      - server
    networks:
      - videome-network-dev
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1
    command: sh -c "npm install && npm run dev"

volumes:
  mongodb_data:
    driver: local
  server_node_modules:
  client_node_modules:

networks:
  videome-network-dev:
    driver: bridge 